/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * unix timestamp in ms
 */
export type Time = number;
/**
 * Type of the block
 */
export type BlockType = string;
/**
 * An explanation about the purpose of this instance.
 */
export type Text = string;
/**
 * An explanation about the purpose of this instance.
 */
export type Level = number;
/**
 * editorjs blocks.
 */
export type Blocks = Block[];
/**
 * editorjs version
 */
export type Version = string;

/**
 * The root schema comprises the entire JSON document.
 */
export interface EditorJsDoc {
  time: Time;
  blocks: Blocks;
  version: Version;
  [k: string]: unknown;
}
/**
 * Block of text
 */
export interface Block {
  type: BlockType;
  data: Data;
  [k: string]: unknown;
}
/**
 * Data stored in a block
 */
export interface Data {
  text: Text;
  level?: Level;
  [k: string]: unknown;
}
